import GameCard from "~/components/GameCard";

export default function Games () {
  return (
    <div class="w-full h-[calc(100%-64px)]">
      <div class="flex flex-col justify-center items-center h-1/2">
        <h1 class="text-4xl">Games</h1>
        
      </div>
      <div class="grid gap-6 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 p-6">
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
        <GameCard name="Tetris" img="/img/tetris.webp" description="Tetris is the addictive puzzle game that started it all, embracing our universal desire to create order out of chaos. The Tetris game was created by Alexey Pajitnov in 1984—the product of Alexey's computer programming experience and his love of puzzles. In the decades to follow, Tetris became one of the most successful and recognizable video games, appearing on nearly every gaming platform available. This page is the official destination for free online single-player Tetris. Click PLAY to start playing one of the world's most popular puzzle games now!" tags="puzzle" url="/game/tetris" image="" />
      </div>
    </div>
  )
}
